version: "3.4"

services:
  test_back:
    image: test_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - ./backend/.env
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/usr/src/app/