version: "3.4"

services:
  test_back:
    image: test_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - ./backend/.env
    ports:
      - 3001:3001
    volumes:
      - ./backend/:/usr/src/app/

  test_front:
    image: test_front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn dev
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app/